### ISSUE TITLE
move the tara project in the online tercen under explore, tercen project

### ISSUE THREAD

**Issue by marionlibouban** [tercen/tara_gorsky2016_workflow_guide#12]

**Comment by marionlibouban** [comment]
@amaurel , I do not see any of the project on the "real" tercen, all is at the moment on the stage version. I need to provide a link to Dave, the goal is to navigate from the website directly to the project on the real tercen. 
Can you guide AlexG and I on what to do here?

**Comment by marionlibouban** [comment]
@agouy  you can migrate your work to the online version of tercen, the one you can login from the website

**Comment by agouy** [comment]
@marionlibouban can you confirm I should create an account on **tercen.com** and move the things I did on **stage.tercen.com** there?

**Comment by marionlibouban** [comment]
@agouy yes and join the tercen team

**Comment by agouy** [comment]
@marionlibouban how can I join the tercen team ?

**Comment by marionlibouban** [comment]
@agouy  I moved it.  You better work from there now because you will have to import everything again. I will close the issue.
