### ISSUE TITLE
readme file: topic description, data process, instruments, stats, operators, visuals

### ISSUE THREAD

**Issue by marionlibouban** [tercen/tara_gorsky2016_workflow_guide#2]
* README: project description (same as website)
* data processing steps
* instruments, stats, operators+ explanation what and how it does
* visuals
* scientific conclusions

**Comment by agouy** [comment]
To do:
* README: project description (same as website)
* data processing steps
* instruments, stats, operators+ explanation what and how it does
* visuals
* scientific conclusions
