### ISSUE TITLE
Second part of workflow: map creation

### ISSUE THREAD

**Issue by marionlibouban** [tercen/tara_gorsky2016_workflow_guide#7]
Tasks:

- [x] build a data processing workflow in Tercen to prepare map input

- [x] create a shiny operator to make the map

**Comment by agouy** [comment]
Update: map operator is working now. Just need to find a way to build docker image and it should work.

**Comment by agouy** [comment]
Update: docker image now works and everything is ready. Tercen requires an update before deplyment of the new operator
